language: python
python:
  - "2.7"
sudo: false
cache:
  directories:
    - "~/.platformio"
install:
  - pip install -U platformio
  - platformio update
before_script:
  - cp src/config.example.h src/config.h
  - cp platformio.example.ini platformio.ini
script:
  - platformio run
